#! /bin/sh -f

# /** ------------------------------------------------------------------------- *
#  * libpomdp
#  * ========
#  * File: matbg
#  * Description: 
#  * Copyright (c) 2009, 2010 Diego Maniloff 
#  * W3: http://www.cs.uic.edu/~dmanilof
#  --------------------------------------------------------------------------- */

# Clear the DISPLAY.
unset DISPLAY  # unset DISPLAY for some shells
# Call MATLAB with the appropriate input and output,
# make it immune to hangups and quits using ''nohup'',
# and run it in the background.
nohup matlab -nodisplay -nodesktop -nosplash < $1 > /dev/null &
